api_url = 'https://image.tmdb.org/t/p/w500'
const moviesDatabase =
    [
       {
           
           "id": 843633,
           "original_language": "en",
           "overview": "An ex-marine enforcer must battle his conscience and code of honor when he is forced to do things for the mob.",
           "popularity": 1522.228,
           "poster_path": api_url + "/lG56H40Y1BuHSPoWtEgDJsSgDBZ.jpg",
           "release_date": "2022-06-03",
           "title": "White Elephant",
       },
       {
           "id": 960700,
           "original_language": "ja",
           "overview": "The Elric brothers meet their toughest opponent yet — a lone serial killer with a large scar on his forehead.",
           "popularity": 1454.607,
           "poster_path": api_url + "/c5OwwBNyJkwyroIOIJL9IiRjydR.jpg",
           "release_date": "2022-05-20",
           "title": "Fullmetal Alchemist: The Revenge of Scar",
       },
       {
           "id": 361743,
           "original_language": "en",
           "overview": "After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.",
           "popularity": 1580.086,
           "poster_path": api_url + "/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
           "release_date": "2022-05-24",
           "title": "Top Gun: Maverick",
       },
       {
           "id": 756999,
           "original_language": "en",
           "overview": "Finney Blake, a shy but clever 13-year-old boy, is abducted by a sadistic killer and trapped in a soundproof basement where screaming is of little use. When a disconnected phone on the wall begins to ring, Finney discovers that he can hear the voices of the killer’s previous victims. And they are dead set on making sure that what happened to them doesn’t happen to Finney.",
           "popularity": 1561.743,
           "poster_path": api_url + "/lr11mCT85T1JanlgjMuhs9nMht4.jpg",
           "release_date": "2021-06-24",
           "title": "The Black Phone",
       },
       {
           "id": 773867,
           "original_language": "ko",
           "overview": "Chasing speed, dreams and money, a team of drivers get involved in the slush fund investigation of a powerful figure during the 1988 Seoul Olympics.",
           "popularity": 1247.247,
           "poster_path": api_url + "/txaOvJ6HURmqFbpVtJezWNWqaR4.jpg",
           "release_date": "2022-08-26",
           "title": "Seoul Vibe",
       },
       {
           "id": 675353,
           "original_language": "en",
           "overview": "After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.",
           "popularity": 1170.63,
           "poster_path": api_url + "/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg",
           "release_date": "2022-03-30",
           "title": "Sonic the Hedgehog 2",
       },
       {
           "id": 429473,
           "original_language": "en",
           "overview": "A young girl is kidnapped during a powerful storm. Her mother joins forces with her mysterious neighbour to set off in pursuit of the kidnapper. Their journey will test their limits and expose the dark secrets of their past.",
           "popularity": 1500.96,
           "poster_path": api_url + "/djM2s4wSaATn4jVB33cV05PEbV7.jpg",
           "release_date": "2022-09-23",
           "title": "Lou",
       },
       {
           "id": 773975,
           "original_language": "en",
           "overview": "Recently widowed mom Brenda fights to protect her family during a harrowing road trip when a murder and a missing bag of cash plunge them into danger.",
           "popularity": 1176.941,
           "poster_path": api_url + "/tLFIMuPWJHlTJ6TN8HCOiSD6SdA.jpg",
           "release_date": "2022-09-09",
           "title": "End of the Road",
       },
       {
           "id": 76600,
           "original_language": "en",
           "overview": "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
           "popularity": 1162.159,
           "poster_path": api_url + "/1yppMeTNQwDrzaUH4dRCx4mr8We.jpg",
           "release_date": "2022-12-14",
           "title": "Avatar: The Way of Water",
       },
       {
           "id": 634649,
           "original_language": "en",
           "overview": "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
           "popularity": 1143.422,
           "poster_path": api_url + "/uJYYizSuA9Y3DCs0qS4qWvHfZg4.jpg",
           "release_date": "2021-12-15",
           "title": "Spider-Man: No Way Home",
       },
       {
           "id": 585511,
           "original_language": "en",
           "overview": "Suddenly finding herself in the never-before-seen Land of Luck, the unluckiest person in the world must unite with the magical creatures there to turn her luck around.",
           "popularity": 1006.376,
           "poster_path": api_url + "/1HOYvwGFioUFL58UVvDRG6beEDm.jpg",
           "release_date": "2022-08-05",
           "title": "Luck",
       },
       {
           "id": 952374,
           "original_language": "en",
           "overview": "A twisted journey of two women’s desperate flee to escape the clutches of Skylight, an insidious cult. Lured in by the promise of “freedom” in the isolated desert campus called The Aviary, Jillian and Blair join forces to escape in hopes of real freedom. Consumed by fear and paranoia, they can’t shake the feeling that they are being followed by the cult’s leader, Seth, a man as seductive as he is controlling. The more distance the pair gains from the cult, the more Seth holds control of their minds. With supplies dwindling and their senses failing, Jillian and Blair are faced with a horrifying question: how do you run from an enemy who lives inside your head?",
           "popularity": 1042.845,
           "poster_path": api_url + "/u6HUQcOQsgkFFO8xCITfxQz6ivc.jpg",
           "release_date": "2022-04-29",
           "title": "The Aviary",
       },
       {
           "id": 1015602,
           "original_language": "en",
           "overview": "Heart set on becoming a princess, Lisa Simpson is surprised to learn being bad might be more fun.",
           "popularity": 964.352,
           "poster_path": api_url + "/kxB9E6fo0ycHzd13oOTHmGa5Njd.jpg",
           "release_date": "2022-09-08",
           "title": "Welcome to the Club",
       },
       {
           "id": 453395,
           "original_language": "en",
           "overview": "Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.",
           "popularity": 1062.248,
           "poster_path": api_url + "/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg",
           "release_date": "2022-05-04",
           "title": "Doctor Strange in the Multiverse of Madness",
       },
       {
           "id": 838197,
           "original_language": "it",
           "overview": "Carezza and Sorriso, brothers very different from each other and in quarrel since childhood, will have to put aside their controversies to recover the legendary Dune Buggy, once belonged to their beloved father and now stolen from him by Torsillo, an unscrupulous building speculator, and his son Raniero. In doing so, they will forge an unusual alliance with a circus community, headed by the beautiful and dangerous Miriam and threatened by Torsillo's dirty business. Between daring chases, memorable fights and delicate meals based on beer and sausages, will the two brothers be able to find their beloved car?",
           "popularity": 1132.642,
           "poster_path": api_url + "/qlrRi05x5hjoM29hz6TDLGTUSop.jpg",
           "release_date": "2022-03-23",
           "title": "Watch Out, We're Mad",
       },
       {
           "id": 936897,
           "original_language": "en",
           "overview": "Goldy is a spirited single mom who’s thrust into the role of town sleuth to help solve a friend’s mysterious death. With the clock ticking to find the culprit, Goldy strikes up an unlikely partnership with Detective Tom Schultz, who leans into Goldy’s local knowledge. As their relationship shows signs of becoming something more, the suspect list rises. Will Goldy narrow in on the killer before the killer narrows in on her?",
           "popularity": 929.654,
           "poster_path": api_url + "/7quPRcCVUmMBxKO58QwPuIADtYG.jpg",
           "release_date": "2022-04-10",
           "title": "Curious Caterer: Dying for Chocolate",
       },
       {
           "id": 804413,
           "original_language": "en",
           "overview": "Lily is a typical 150-year-old lovelorn vampire who's looking for the man of her nightmares -- until she lays her eyes on Herman, a 7-foot-tall green experiment with a heart of gold. It's love at first shock as these two ghouls fall fangs over feet for each other in a Transylvanian romance. Unfortunately, it's not all smooth sailing in the cemetery as Lily's father has other plans for his beloved daughter's future, and they don't involve her new bumbling beau.",
           "popularity": 1013.794,
           "poster_path": api_url + "/kJaEVFhDouD72GKANMkYqzQky9n.jpg",
           "release_date": "2022-09-27",
           "title": "The Munsters",
       },
       {
           "id": 762504,
           "original_language": "en",
           "overview": "Residents in a lonely gulch of inland California bear witness to an uncanny, chilling discovery.",
           "popularity": 1035.668,
           "poster_path": api_url + "/AcKVlWaNVVVFQwro3nLXqPljcYA.jpg",
           "release_date": "2022-07-20",
           "title": "Nope",
       },
       {
           "id": 924482,
           "original_language": "en",
           "overview": "A rock climbing adventure between two friends turns into a terrifying nightmare. After Kelly captures the murder of her best friend on camera, she becomes the next target of a tight knit group of friends who will stop at nothing to destroy the evidence and anyone in their way. Desperate for her safety, she begins a treacherous climb up a mountain cliff and her survival instincts are put to the test when she becomes trapped with the killers just 20 feet away.",
           "popularity": 941.823,
           "poster_path": api_url + "/dHKfsdNcEPw7YIWFPIhqiuWrSAb.jpg",
           "release_date": "2022-02-18",
           "title": "The Ledge",
       },
       {
           "id": 576925,
           "original_language": "ru",
           "overview": "A scandal in the royal family: the wayward princess Barbara escaped from the palace and went through the forest in search of a handsome prince. However, instead of the cherished meeting with her beloved, she is captured by Buka, the most dangerous robber of the kingdom. But it quickly becomes clear that the brisk princess is ready to turn Buka's life into a nightmare, just to reach her goal. So the restless Varvara begins to establish her own order in the forest.",
           "popularity": 880.536,
           "poster_path": api_url + "/xIbEHAqwK5N7PJJYmbwmxuvC7fL.jpg",
           "release_date": "2022-01-27",
           "title": "My Sweet Monster",
       }
]

module.exports = moviesDatabase;